---
server:
  port: 8080
  contextPath: /identification

datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/identification
    username: root
    password: 123456789
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: none
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

